language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4k-blockchain
  api_key:
    secure: t8ehX/TzNmWKJkwdzdIAK6bZJxJh2VgdWVKIN/23ivHiHx9BQojw9uyWZDb7CCNC2NZ9bAefC0UyP8ay89/i8U4x+XOggfenMrvp2yHPmQ0X5HcWO50kAoTY8zE1nQsk29rfDGEkITtvWIGv9dMQS+pZM8+HvtbMoVnpVtdbQfE2XXVi7DJV6gwz2xGOj3juqDYVe0kxvqIcoDOErNCxs4g2FQAVkxL/BMJUJdKxtrVYW0J2qTh+bdlqP1DbSIE9rblSn7ycbmcumlRMrd+UYuDZZUHdmpE5T6DwcAjjbUlj7Sto0CcV8qCxFgR5JeBA/OHmZusL45LBtS6kg1/eGbqgvHC+QPDa93ur5k8BkOMnhD+hv75cf/0WdKsMdjX5qHya+pJR7G5QIPde7kxoicVTgKyHCXkSziefoNFwkKfKzJu19qrfrO7cW1MdCB0TB6UQ1jm/kNTm7G0EGdF4qWTlaauID9PftH60lwUMO17ClPRKPP1axePoVgHA+rO4IR8OZgpQTgtnJ5ol+iGXpt7MhkS5n4sfLrn4upGvRMlsiHivITTzeY5ywlcy0t2SUFEhCzMqmbZATio0wnueD/tJ9/DOKlkfMVva7uUaTBU0UY/OpzgHo/w4nqTmkwjGayNkS8E22lIXtNKJWNFYLIQB8p6uXeMDWq21qAG/RsI=
